services:
  meshmonitor:
    image: ghcr.io/yeraze/meshmonitor:latest
    container_name: meshmonitor
    ports:
      - "8080:3001"
    restart: unless-stopped
    volumes:
      - meshmonitor-data:/data
    environment:
      - MESHTASTIC_NODE_IP=${deTemp_IP}
      - ALLOWED_ORIGINS=http://localhost:8080
      - SESSION_SECRET=${SESSION_STRING}
      - TRUST_PROXY=true 
      - COOKIE_SECURE=true
      - ALLOWED_ORIGINS=https://meshmonitor.example.com

volumes:
  meshmonitor-data:
    driver: local